version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app # Change this accordingly, if you clone this repo then this is okay.
    ports:
      - 8092:3000
    command: "npm start"
