version: "2"
services:
  node:
    build: ./
    working_dir: /usr/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 8092:3000
    command: "npm start"
