version: "3"

name: la3map
services:
  node:
    build: ./
    working_dir: /usr/app
    environment:
      - NODE_ENV=production
      - IS_DOCKER=true
    ports:
      - ${APP_PORT}:3000
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3000/healthcheck"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    command: "npm start"
    restart: unless-stopped
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
  postgres:
    env_file: .env
    image: postgis/postgis:12-3.3
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_EXT_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
